### ISSUE TITLE
Plugin not visible into IntelliJ Idea 2018.1.3 

### ISSUE THREAD

**Issue by parveenkumardeeva** [heyuxian/code-generator#1]
Hi, Your Plugin is no more visible into IntelliJ Idea 2018.1.3 . And I was using it into AS but now it's saying it's not compatible anymore.

Please update the Plugin as soon as possible because my projects are dependent on it.

**Comment by heyuxian** [comment]
I have updated the plugin, please go to the [release page](https://github.com/heyuxian/code-generator/releases/tag/V1.2.0.RELEASE) to download the latest plugin package.

**Comment by parveenkumardeeva** [comment]
Dear I think it's not working. Installed via zip file.

Here is the screenshot. Please found what's the issue. It's Mac, working fine onto the Linux OS (But it's have old Intellij Version).
<img width="1271" alt="screen shot 2018-05-17 at 10 24 12 am" src="https://user-images.githubusercontent.com/16252073/40157470-dddb80b6-59bc-11e8-936b-08cfb05c8569.png">

**Comment by heyuxian** [comment]
Sorry, some errors may have occurred when I packaged the plugins. I have repackaged the plugin and uploaded it to the GitHub release. Please download and install it again.

**Comment by parveenkumardeeva** [comment]
Hey , Thanks Buddy.
It's working fine now.

**Comment by parveenkumardeeva** [comment]
Dear,

The plugin is not behaving properly. After using it once that day I tried to use this plugin today. 
But there is nothing there.

I found these following problems:

1. Export option not working.
2. Without creating group you can't create template.
3. May be we can't import templates. Please provide an example if you can.
4. Default group is no more visible now.
## 5. The main problem:

###  If we restart the Intellij Idea then all work got lost about the templates. Means all group templates got lost somewhere.

I think you are using deprecated API's of the Intellij Idea. Checked on Mac and Linux systems. Will you please have a look?

**Comment by heyuxian** [comment]
So long to reply, I'm sorry.

> 1. Export option not working.
> 2. May be we can't import templates. Please provide an example if you can.
> 4. Default group is no more visible now.
> 5. The main problem

Please **reinstall** [the latest version](https://github.com/heyuxian/code-generator/releases/tag/V1.2.1.RELEASE) of the plugin.

> 2.Without creating group you can't create template.

Template must be in a group.

**Comment by parveenkumardeeva** [comment]
Hi Heyuxian,

Sorry to disturb you again.

Can you please update this plugin with the latest version of Intellij Idea?
I shall be very thankful to you.

**Comment by heyuxian** [comment]
@parveenkumardeeva  please use: [Code.Generator-1.3.0.RELEASE.zip](https://github.com/heyuxian/code-generator/releases/download/1.3.0.RELEASE/Code.Generator-1.3.0.RELEASE.zip)

**Comment by parveenkumardeeva** [comment]
Hey, thanks a lot again.
